blank_issues_enabled: true
contact_links:
  - name: project set
    about: project set template
    url: https://github.com/tubasa17/study-session/issues/new?projects=tubasa17/1&template=abceds.md&labels=bug
